### ISSUE TITLE
How to intercept https traffic?

### ISSUE THREAD

**Issue by Miraj50** [sgr-io/docker-mitmproxy#1]

**Comment by Miraj50** [comment]
Sorry, got it. The certificate was wrong.

**Comment by SgrAlpha** [comment]
Never mind, the self-signed certificates will be save at `~/.mitmproxy`, port 8080 will be mapped to your host, and you can point your proxy to localhost:8080, and you will see logs in docker by using `docker logs -f <your_container_name>`
